### ISSUE TITLE
Тут у меня ошибка

### ISSUE THREAD

**Issue by tailsjs** [VKCOM/vk-qr#11]
Отправляю запрос:
```js
const qr = require('@vkontakte/vk-qr');
const text = 'TEST'; 
const isShowVkLogo = true; 
const qrSvg = qr.createQR(text, 256, 'qr-code-class', isShowVkLogo); 
document.body.innerHTML = qrSvg;
```
Возвращается:
```js
SyntaxError: Unexpected token export
```

**Comment by danakt** [comment]
@tailsjs в `dist` есть разные версии бандлов для разных систем модулей. Можно делать так:
> const qr = require('@vkontakte/vk-qr/dist/cjs/index.js');

**Comment by tailsjs** [comment]
Спасибо, ошибка пропала только ещё один вопрос...
Откуда брать document?
У меня тут просто ошибка 
`ReferenceError: document is not defined`

**Comment by danakt** [comment]
@tailsjs `document` не используется в коде. В каком месте ошибка возникает?

**Comment by tailsjs** [comment]
В `document`

**Comment by danakt** [comment]
@tailsjs это явно не на стороне библиотеки, потому что она не работает с DOM'ом. Основной вопрос решен: в качестве главной системы модулей теперь используется commonjs-бандл.
